# Generated by Django 3.2.8 on 2021-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
