# Generated by Django 3.2.8 on 2021-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
